package logan.neo4j;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class CypherExtractorTest {

    @Test
    void extractTest () {
        assertEquals("-  - MATCH  \t\t(adAccount:ENTITY {enabled: true, property_type: 'AdAccount'}) \t\t-[:HAS_CREDENTIAL]->(c:CREDENTIAL {enabled: true}) \t\tWHERE  \t\t\tc.up_user_id CONTAINS \"\"horizon\"\" AND (adAccount.network IN [\"\"gam\"\"]) \t\tWITH  \t\t\tcollect(DISTINCT adAccount.property_id) AS ignoredAdAccountIds \t MATCH          (principleCampaign:PrincipleCampaign) \t\tWHERE \t\tNOT principleCampaign.startDate IS NULL \t\t\tAND principleCampaign.spentToDate > 0 \t\t\tAND NOT principleCampaign.adAccountId IN ignoredAdAccountIds  \t\t\tAND NOT EXISTS((principleCampaign)<-[:CONTEXTING_TO]-(:LineItem)) \t\t\t AND (principleCampaign.publisher IN [\"\"gam\"\"])  AND ( \t\t\t\t\t(principleCampaign.endDate IS NULL OR (principleCampaign.startDate <= (timestamp() / 1000) <= principleCampaign.endDate)) \t\t\t\t\t) \t\tWITH  \t\t\tprincipleCampaign \t RETURN  \t\tDISTINCT principleCampaign.id as id, \t\tprincipleCampaign.adAccountTimezone as accountTimezone, \t\tprincipleCampaign.adAccountId as adAccountId, \t\tprincipleCampaign.adAccountName as adAccountName, \t\tprincipleCampaign.endDate as endDate, \t\tprincipleCampaign.objective as objective, \t\tprincipleCampaign.name as name, \t\tprincipleCampaign.publisher as publisher, \t\tprincipleCampaign.startDate as startDate \t ORDER BY CASE principleCampaign.id WHEN toString(principleCampaign.id) THEN toLower(principleCampaign.id + '') ELSE principleCampaign.id END ASC SKIP $0 LIMIT $1 - {0:", CypherExtractor.extract("""
                                                     "Oct 18, 2024 @ 23:59:54.712","2024-10-18 23:59:54.712+0000 INFO  5610 ms: 99547072 B - bolt-session	bolt	Go Driver/4.3		client/10.30.0.205:34880	server/10.30.101.199:9000>	neo4j -  - MATCH  		(adAccount:ENTITY {enabled: true, property_type: 'AdAccount'}) 		-[:HAS_CREDENTIAL]->(c:CREDENTIAL {enabled: true}) 		WHERE  			c.up_user_id CONTAINS ""horizon"" AND (adAccount.network IN [""gam""]) 		WITH  			collect(DISTINCT adAccount.property_id) AS ignoredAdAccountIds 	 MATCH          (principleCampaign:PrincipleCampaign) 		WHERE 		NOT principleCampaign.startDate IS NULL 			AND principleCampaign.spentToDate > 0 			AND NOT principleCampaign.adAccountId IN ignoredAdAccountIds  			AND NOT EXISTS((principleCampaign)<-[:CONTEXTING_TO]-(:LineItem)) 			 AND (principleCampaign.publisher IN [""gam""])  AND ( 					(principleCampaign.endDate IS NULL OR (principleCampaign.startDate <= (timestamp() / 1000) <= principleCampaign.endDate)) 					) 		WITH  			principleCampaign 	 RETURN  		DISTINCT principleCampaign.id as id, 		principleCampaign.adAccountTimezone as accountTimezone, 		principleCampaign.adAccountId as adAccountId, 		principleCampaign.adAccountName as adAccountName, 		principleCampaign.endDate as endDate, 		principleCampaign.objective as objective, 		principleCampaign.name as name, 		principleCampaign.publisher as publisher, 		principleCampaign.startDate as startDate 	 ORDER BY CASE principleCampaign.id WHEN toString(principleCampaign.id) THEN toLower(principleCampaign.id + '') ELSE principleCampaign.id END ASC SKIP $0 LIMIT $1 - {0: 6000, 1: 500} - runtime=pipelined - {}\""""));
    }
}
